### ISSUE TITLE
mouse coursor , scroll button , and light mode feature

### ISSUE THREAD

**Issue by Dipeshdahiya** [priyamaggarwal18/Portfolio#2]
Hi @priyamaggarwal18 , I would like to remove the bug of mouse cursor pointer , even the scroll button hovering on and off , even if you like i would also want to add on a light mode to you portfolio.
Please assign this issue to me.

**Comment by priyamaggarwal18** [comment]
ok go for it I have also Assigned the hacktoberfest and enhancement tags to this issue.

**Comment by Dipeshdahiya** [comment]
could you please add gssoc and gssoc24 label as well was to this issue

**Comment by priyamaggarwal18** [comment]
done

**Comment by priyamaggarwal18** [comment]
this issue is closed in the refrence of #5
