### ISSUE TITLE
Incorrect grammer  in "About Us" section 

### ISSUE THREAD

**Issue by wgeenath** [priyamaggarwal18/Portfolio#6]
informal content  in "About Us" section 

<img width="454" alt="QA1728528302" src="https://github.com/user-attachments/assets/cd557282-39be-4984-a914-afa01629028f">

"was that average student" → It should be "was an average student". Use "an" instead of "that" because "that" is too informal in this context and doesn't fit the general description.

Kindly put hacktoberfest2024 labels and assign me to fix this

**Comment by priyamaggarwal18** [comment]
sry @wgeenath  but I don't promote these types of contributions.. please make a detailed contribution like adding new section or updating readme.
